 /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Avatar(props) {
  const { nodes, materials } = useGLTF('/models/untitled1.glb');
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.spine} />
      <primitive object={nodes.thumb01L} />
      <skinnedMesh
        geometry={nodes.Genesis9TearShape001.geometry}
        material={materials.Tear}
        skeleton={nodes.Genesis9TearShape001.skeleton}
      />
      <primitive object={nodes.root} />
      <primitive object={nodes['MCH-torsoparent']} />
      <primitive object={nodes['MCH-hand_ikparentL']} />
      <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
      <primitive object={nodes['MCH-hand_ikparentR']} />
      <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
      <primitive object={nodes['MCH-eye_commonparent']} />
      <primitive object={nodes['MCH-foot_ikparentL']} />
      <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
      <primitive object={nodes['MCH-foot_ikparentR']} />
      <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
      <primitive object={nodes['MCH-lip_armBL001']} />
      <primitive object={nodes['MCH-lip_armBR001']} />
      <primitive object={nodes['MCH-lip_armTL001']} />
      <primitive object={nodes['MCH-lip_armTR001']} />
      <primitive object={nodes.neutral_bone} />
      <skinnedMesh
        geometry={nodes.Bra_5382002.geometry}
        material={materials.Bra_Heart}
        skeleton={nodes.Bra_5382002.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Bra_5382002_1.geometry}
        material={materials.Bra_Main}
        skeleton={nodes.Bra_5382002_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Bra_5382002_2.geometry}
        material={materials.Bra_Upper_Border}
        skeleton={nodes.Bra_5382002_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Bra_5382002_3.geometry}
        material={materials.Bra_Straps}
        skeleton={nodes.Bra_5382002_3.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Bra_5382002_4.geometry}
        material={materials.Bra_Underbust}
        skeleton={nodes.Bra_5382002_4.skeleton}
      />
      <skinnedMesh
        geometry={nodes.EssentialShortsG9002.geometry}
        material={materials.Trim}
        skeleton={nodes.EssentialShortsG9002.skeleton}
      />
      <skinnedMesh
        geometry={nodes.EssentialShortsG9002_1.geometry}
        material={materials.Pants}
        skeleton={nodes.EssentialShortsG9002_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.EssentialShortsG9002_2.geometry}
        material={materials.Waistband}
        skeleton={nodes.EssentialShortsG9002_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.G9EyebrowCards002.geometry}
        material={materials.Eyebrows_Primary}
        skeleton={nodes.G9EyebrowCards002.skeleton}
      />
      <skinnedMesh
        geometry={nodes.G9EyebrowCards002_1.geometry}
        material={materials.Eyebrows_Secondary}
        skeleton={nodes.G9EyebrowCards002_1.skeleton}
      />
      <skinnedMesh
        name="Genesis9002"
        geometry={nodes.Genesis9002.geometry}
        material={materials.Fingernails}
        skeleton={nodes.Genesis9002.skeleton}
        morphTargetDictionary={nodes.Genesis9002.morphTargetDictionary}
        morphTargetInfluences={nodes.Genesis9002.morphTargetInfluences}
      />
      <skinnedMesh
        name="Genesis9002_1"
        geometry={nodes.Genesis9002_1.geometry}
        material={materials.Toenails}
        skeleton={nodes.Genesis9002_1.skeleton}
        morphTargetDictionary={nodes.Genesis9002_1.morphTargetDictionary}
        morphTargetInfluences={nodes.Genesis9002_1.morphTargetInfluences}
      />
      <skinnedMesh
        name="Genesis9002_2"
        geometry={nodes.Genesis9002_2.geometry}
        material={materials.Legs}
        skeleton={nodes.Genesis9002_2.skeleton}
        morphTargetDictionary={nodes.Genesis9002_2.morphTargetDictionary}
        morphTargetInfluences={nodes.Genesis9002_2.morphTargetInfluences}
      />
      <skinnedMesh
        name="Genesis9002_3"
        geometry={nodes.Genesis9002_3.geometry}
        material={materials['Mouth Cavity']}
        skeleton={nodes.Genesis9002_3.skeleton}
        morphTargetDictionary={nodes.Genesis9002_3.morphTargetDictionary}
        morphTargetInfluences={nodes.Genesis9002_3.morphTargetInfluences}
      />
      <skinnedMesh
        name="Genesis9002_4"
        geometry={nodes.Genesis9002_4.geometry}
        material={materials.Arms}
        skeleton={nodes.Genesis9002_4.skeleton}
        morphTargetDictionary={nodes.Genesis9002_4.morphTargetDictionary}
        morphTargetInfluences={nodes.Genesis9002_4.morphTargetInfluences}
      />
      <skinnedMesh
        name="Genesis9002_5"
        geometry={nodes.Genesis9002_5.geometry}
        material={materials.Head}
        skeleton={nodes.Genesis9002_5.skeleton}
        morphTargetDictionary={nodes.Genesis9002_5.morphTargetDictionary}
        morphTargetInfluences={nodes.Genesis9002_5.morphTargetInfluences}
      />
      <skinnedMesh
        name="Genesis9002_6"
        geometry={nodes.Genesis9002_6.geometry}
        material={materials.Body}
        skeleton={nodes.Genesis9002_6.skeleton}
        morphTargetDictionary={nodes.Genesis9002_6.morphTargetDictionary}
        morphTargetInfluences={nodes.Genesis9002_6.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Genesis9Eyelashes002.geometry}
        material={materials['Eyelashes Lower']}
        skeleton={nodes.Genesis9Eyelashes002.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Genesis9Eyelashes002_1.geometry}
        material={materials['Eyelashes Upper']}
        skeleton={nodes.Genesis9Eyelashes002_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Genesis9Eyes002.geometry}
        material={materials['EyeMoisture Left']}
        skeleton={nodes.Genesis9Eyes002.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Genesis9Eyes002_1.geometry}
        material={materials['Eye Left']}
        skeleton={nodes.Genesis9Eyes002_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Genesis9Eyes002_2.geometry}
        material={materials['Eye Right']}
        skeleton={nodes.Genesis9Eyes002_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Genesis9Eyes002_3.geometry}
        material={materials['EyeMoisture Right']}
        skeleton={nodes.Genesis9Eyes002_3.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Genesis9Mouth002.geometry}
        material={materials.Mouth}
        skeleton={nodes.Genesis9Mouth002.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Genesis9Mouth002_1.geometry}
        material={materials.Teeth}
        skeleton={nodes.Genesis9Mouth002_1.skeleton}
      />
    </group>
  )
}

useGLTF.preload('/untitled1.glb')
